USE TRENDS;

CREATE TABLE NOTES
(
	NOTE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NOTE VARCHAR(255) NOT NULL,
	NOTE_DATE DATE NOT NULL 
);

CREATE TABLE MOODS
(
	MOOD_ID VARCHAR(36) NOT NULL PRIMARY KEY,
	MOOD INTEGER NOT NULL,
	MOOD_DATE DATE NOT NULL
);

DELIMITER ;;

CREATE TRIGGER before_insert_notes
BEFORE INSERT ON NOTES
FOR EACH ROW
BEGIN
  IF new.NOTE_ID IS NULL THEN
    SET new.NOTE_ID = uuid();
  END IF;
END
;;

CREATE TRIGGER before_insert_mood
BEFORE INSERT ON MOODS
FOR EACH ROW
BEGIN
  IF new.MOOD_ID IS NULL THEN
    SET new.MOOD_ID = uuid();
  END IF;
END
;;

DELIMITER ;

CREATE USER 'Dev' IDENTIFIED BY 'letmein';
GRANT ALL PRIVILEGES ON TRENDS.* TO 'Dev';
FLUSH PRIVILEGES;

INSERT INTO TRENDS.NOTES (NOTE_ID, NOTE, NOTE_DATE) 
VALUES 
("TEST_00001", "Hello 1" , "2005-02-01"),
("TEST_00002", "Hello 2" , "2012-02-02"),
("TEST_00003", "World Hello 2" , "1998-05-01"),
("TEST_00004", "We lost at Rocket League", "2018-03-02");

INSERT INTO TRENDS.MOODS (MOOD_ID, MOOD, MOOD_DATE)
VALUES
("TEST_MOOD_00001", 5, "2018-03-01"),
("TEST_MOOD_00002", 2, "2018-03-02"),
("TEST_MOOD_00003", 6, "2018-03-03");